# Generated by Django 3.0.5 on 2021-05-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOperation', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('resultat', models.TextField()),
                ('validation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDeSejour', models.DateField(null=True)),
                ('dateDeFinSejour', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comptRendu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.TextField()),
                ('dateDeCreation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOperation', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('resultat', models.TextField()),
                ('validation', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aboutPatient.Consultation')),
            ],
        ),
    ]
