# Generated by Django 3.0.5 on 2021-05-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('aboutPatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='docteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idDocteurRadio', to='users.Docteur'),
        ),
        migrations.AddField(
            model_name='radio',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idPatientRadio', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='docteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idDocteurPrescription', to='users.Docteur'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idPatientPrescription', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_patient', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='chambre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chambre', to='aboutPatient.Chambre'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='docteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docteur', to='users.Docteur'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dossier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='aboutPatient.Dossier'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription', to='aboutPatient.Prescription'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='docteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idDocteurChambre', to='users.Docteur'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idPatientChambre', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aboutPatient.Consultation'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='docteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idDocteurAnalyse', to='users.Docteur'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idPatientAnalyse', to='users.Patient'),
        ),
    ]
