# Generated by Django 3.0.5 on 2021-06-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPatient', '0002_auto_20210529_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyse',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='consultation',
        ),
    ]
